travis:
  secure:
    BINSTAR_TOKEN: ahA0sUBfrsSxpYWr/OPG1VHAj4BJvHYKYtpB8F/U1oRhjuJ9yIM0lIqAZkqdjgE2fXhK0f/uXei6mTZ0/i3uJlEqVLDALDP2MUAf2Hboc09lGxU58UTazX8fOZTzHuuZnuK4FFGa5O2AtSJefvTobu/72UlUNfUq88IgVRJETDZtxnlnvN15gpQ42br3mZ+KGHW+jd2mZ+DnZkxyXX6X+Y19r+zv+gRiDgbM/QDvzUUJVmoNIrWH/sgqCzGlXFSWMYuBMqZO/Tg+y3cVpmDhEdQk2yAI6hD3TW5RJRipbs/IHugLHGK083UN96UGTBOLLHjxBYi63wcMxeIn/dWrTK2ncmMkXQTzfDpZt47GZU0Yvmf9rQjS7iVmumzxw5XQPaY/QQCnnBoh9OD2my9ERlhpk0xd9jRdPlKJiKzlG2PMYTMXcc7BDKEfZX3C1YZhpQK9VZPh8vxbe/1H9kgAmNzoWO3aV8BXlyGERPCxjmY8R++mZshFf/kk+6oDDA7/znsiLciL5MULQPQMjMj6aEzixfehnOd3+rFKTHYq05pvHMBJOV/Hgh+BFqtGqAgfkjgUf37s77HwNxtVphIuZfyLjN7e3111i9BnQTIlKga+KCNINmWRbnfuAn65ADBp+7EAmYxmCSnixVV1JAJOk06w8+kMTkPWk9k4lw3puM8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
